#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

for pyver in "2.7" "3.7"; do
    echo "Running tests with Python $pyver"
    python$pyver ./run-test.py test-*.txt
    echo
    echo
done
